prepare:
  fetch:
    - url: https://8cb7-167-61-195-35.sa.ngrok.io/rubocop.yml
      path: "my_rubocop.yml"

plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-23-0
    config:
      file: my_rubocop.yml
