prepare:
  fetch:
    - url: https://drive.google.com/u/0/uc?id=1PARCc7GXrlMtT3gE_LT-5FnATjzkHadd&export=download
      path: "my_rubocop.yml"

plugins:
  rubocop:
    enabled: true
    config:
      file: my_rubocop.yml
